FROM ubuntu:latest

ENV TZ=Europe/Moscow \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    tzdata \
    apache2 \
    php-fpm \
    php-mysql \
    php-gd \
    php-json \
    php-curl \
    php-mbstring \
    php-xml \
    php-xmlrpc \
    php-soap \
    php-intl \
    php-zip && \
    a2enmod proxy_fcgi actions rewrite setenvif && \
    a2enmod mpm_event && \
    a2dismod mpm_prefork mpm_worker && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 80

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
